default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: babybrito
  password: Pass1234!

development:
  <<: *default
  database: taskManagementAppDB

test:
  <<: *default
  database: taskManagementAppDB

production:
  <<: *default
  database: taskManagementAppDB